### ISSUE TITLE
Issues with the artifact installation (submodule + missing DLMC script)

### ISSUE THREAD

**Issue by guillaumeiooss** [SpRegTiling/spmm-bench#1]
Hello,

I am trying to replicate your artifact on my machine in order to replicate your experiments (and compare with an implementation on my side). However, I encounter some issue when following the instructions.

1) Issue with submodule [Minor]:
When using the first line of your README.md:
    `git clone https://github.com/SpRegTiling/sparse-register-tiling.git --recurse-submodules`
 I have encountered an issue with the submodule `spmm_nano_kernels`, which can be replicated when I try to do a `git submodule update`:
```
Cloning into '[blablabla]/sparse-register-tiling/spmm_nano_kernels'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```
Maybe the issue comes from a slight difference in name: the Github repository is named "spmm-nano-kernels" while the submodule referred (when checking `git submodule init`) is called "spmm_nano_kernels".

In the meantime, I just cloned the submodule repository manually. So, this issue should be minor.

2) Missing script for the benchmark [Major]:
The second line is blocking: `sh download_dlmc.sh`
Indeed, it does not seem there is such script anywhere in the current version of the repository.

Where can I find it?

Thank you for making your artifact publically available, and thank you in advance for your support,
Guillaume I.

**Comment by guillaumeiooss** [comment]
Correction: I just saw the branch name "pldi-artifact" that does contain the script needed.
Therefore, it solves my problem (for now, at least).

Thanks,
Guillaume I.

**Comment by cheshmi** [comment]
Great! I am closing the issue.
